# 修改内嵌 tomcat 端口号；默认为 9003server:
server:
  port: 9003

# 配置 activeMQ 服务器信息
spring:
  activemq:
    broker-url: tcp://192.168.12.168:61616


# 阿里大于那里申请的 accessKey 信息
accessKeyId: LTAI9mm78aeHxAdj
accessKeySecret: IqYKBhLjh8HLxyJR3U5uToVOrwDK7v